"""Correspondance des codes emoji Slack courants vers Unicode."""

EMOJI: dict[str, str] = {
    "smile": "😄", "smiley": "😃", "grinning": "😀", "grin": "😁", "laughing": "😆",
    "sweat_smile": "😅", "joy": "😂", "rolling_on_the_floor_laughing": "🤣",
    "slightly_smiling_face": "🙂", "upside_down_face": "🙃", "wink": "😉", "blush": "😊",
    "innocent": "😇", "heart_eyes": "😍", "kissing_heart": "😘", "yum": "😋",
    "stuck_out_tongue": "😛", "stuck_out_tongue_winking_eye": "😜", "thinking_face": "🤔",
    "neutral_face": "😐", "expressionless": "😑", "no_mouth": "😶", "smirk": "😏",
    "unamused": "😒", "face_with_rolling_eyes": "🙄", "grimacing": "😬", "relieved": "😌",
    "pensive": "😔", "sleepy": "😪", "sleeping": "😴", "mask": "😷", "nerd_face": "🤓",
    "sunglasses": "😎", "confused": "😕", "worried": "😟", "slightly_frowning_face": "🙁",
    "open_mouth": "😮", "astonished": "😲", "flushed": "😳", "pleading_face": "🥺",
    "cry": "😢", "sob": "😭", "scream": "😱", "confounded": "😖", "disappointed": "😞",
    "sweat": "😓", "weary": "😩", "tired_face": "😫", "triumph": "😤", "rage": "😡",
    "angry": "😠", "skull": "💀", "poop": "💩", "hankey": "💩", "clown_face": "🤡",
    "ghost": "👻", "alien": "👽", "robot_face": "🤖", "see_no_evil": "🙈",
    "hugging_face": "🤗", "face_palm": "🤦", "facepalm": "🤦", "shrug": "🤷",
    "partying_face": "🥳", "star-struck": "🤩", "zany_face": "🤪", "exploding_head": "🤯",
    "+1": "👍", "thumbsup": "👍", "-1": "👎", "thumbsdown": "👎", "ok_hand": "👌",
    "wave": "👋", "clap": "👏", "raised_hands": "🙌", "pray": "🙏", "muscle": "💪",
    "point_up": "☝️", "point_right": "👉", "point_left": "👈", "v": "✌️",
    "crossed_fingers": "🤞", "handshake": "🤝", "eyes": "👀", "brain": "🧠",
    "heart": "❤️", "orange_heart": "🧡", "yellow_heart": "💛", "green_heart": "💚",
    "blue_heart": "💙", "purple_heart": "💜", "black_heart": "🖤", "broken_heart": "💔",
    "sparkling_heart": "💖", "100": "💯", "fire": "🔥", "star": "⭐", "sparkles": "✨",
    "boom": "💥", "zap": "⚡", "tada": "🎉", "confetti_ball": "🎊", "balloon": "🎈",
    "gift": "🎁", "trophy": "🏆", "medal": "🏅", "rocket": "🚀", "bulb": "💡",
    "warning": "⚠️", "no_entry": "⛔", "x": "❌", "white_check_mark": "✅",
    "heavy_check_mark": "✔️", "ballot_box_with_check": "☑️", "question": "❓",
    "exclamation": "❗", "bangbang": "‼️", "red_circle": "🔴", "large_green_circle": "🟢",
    "large_blue_circle": "🔵", "arrow_right": "➡️", "arrow_left": "⬅️",
    "arrow_up": "⬆️", "arrow_down": "⬇️", "link": "🔗", "lock": "🔒", "key": "🔑",
    "memo": "📝", "pencil": "📝", "pencil2": "✏️", "calendar": "📆", "date": "📅",
    "clock": "🕐", "hourglass": "⌛", "email": "📧", "envelope": "✉️", "phone": "📞",
    "computer": "💻", "bug": "🐛", "wrench": "🔧", "hammer": "🔨", "gear": "⚙️",
    "chart_with_upwards_trend": "📈", "chart_with_downwards_trend": "📉",
    "bar_chart": "📊", "clipboard": "📋", "pushpin": "📌", "paperclip": "📎",
    "mag": "🔍", "books": "📚", "moneybag": "💰", "coffee": "☕", "beer": "🍺",
    "beers": "🍻", "pizza": "🍕", "cake": "🍰", "birthday": "🎂", "sunny": "☀️",
    "cloud": "☁️", "umbrella": "☂️", "snowflake": "❄️", "rainbow": "🌈",
    "earth_africa": "🌍", "house": "🏠", "car": "🚗", "airplane": "✈️",
    "dog": "🐶", "cat": "🐱", "unicorn_face": "🦄", "see_no_evil_monkey": "🙈",
    "speech_balloon": "💬", "thought_balloon": "💭", "zzz": "💤", "wavy_dash": "〰️",
    "heavy_plus_sign": "➕", "heavy_minus_sign": "➖", "sos": "🆘", "new": "🆕",
    "free": "🆓", "ok": "🆗", "cool": "🆒", "up": "🆙",
}
